version: '3'
services: 
    redis:
        image: redis
        ports:
        - ${REDISPORT}:${REDISPORT}
    server:
        build: .
        restart: always
        ports: 
            - '3000:3000'
        env_file: ./.env
        environment: 
            - REDISHOST=redis
        depends_on:
            - redis